// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/proto/process/process.proto

package processpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessConfig contains configuration for starting a process
type ProcessConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command to run
	Cmd string `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	// Arguments to the command
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// Environment variables
	Envs map[string]string `protobuf:"bytes,3,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Working directory
	Cwd           string `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessConfig) Reset() {
	*x = ProcessConfig{}
	mi := &file_internal_proto_process_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessConfig) ProtoMessage() {}

func (x *ProcessConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessConfig.ProtoReflect.Descriptor instead.
func (*ProcessConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessConfig) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *ProcessConfig) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProcessConfig) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *ProcessConfig) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

// StartRequest is the request to start a new process
type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ProcessConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_internal_proto_process_process_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{1}
}

func (x *StartRequest) GetConfig() *ProcessConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// StartResponse is the response from starting a process
type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_internal_proto_process_process_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{2}
}

func (x *StartResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// ProcessEvent represents an event from a running process
type ProcessEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ProcessEvent_Data
	//	*ProcessEvent_End
	//	*ProcessEvent_Start
	//	*ProcessEvent_Keepalive
	Event         isProcessEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent) Reset() {
	*x = ProcessEvent{}
	mi := &file_internal_proto_process_process_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent) ProtoMessage() {}

func (x *ProcessEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessEvent) GetEvent() isProcessEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ProcessEvent) GetData() *ProcessEvent_DataEvent {
	if x != nil {
		if x, ok := x.Event.(*ProcessEvent_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ProcessEvent) GetEnd() *ProcessEvent_EndEvent {
	if x != nil {
		if x, ok := x.Event.(*ProcessEvent_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *ProcessEvent) GetStart() *ProcessEvent_StartEvent {
	if x != nil {
		if x, ok := x.Event.(*ProcessEvent_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ProcessEvent) GetKeepalive() *ProcessEvent_KeepAlive {
	if x != nil {
		if x, ok := x.Event.(*ProcessEvent_Keepalive); ok {
			return x.Keepalive
		}
	}
	return nil
}

type isProcessEvent_Event interface {
	isProcessEvent_Event()
}

type ProcessEvent_Data struct {
	Data *ProcessEvent_DataEvent `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type ProcessEvent_End struct {
	End *ProcessEvent_EndEvent `protobuf:"bytes,2,opt,name=end,proto3,oneof"`
}

type ProcessEvent_Start struct {
	Start *ProcessEvent_StartEvent `protobuf:"bytes,3,opt,name=start,proto3,oneof"`
}

type ProcessEvent_Keepalive struct {
	Keepalive *ProcessEvent_KeepAlive `protobuf:"bytes,4,opt,name=keepalive,proto3,oneof"`
}

func (*ProcessEvent_Data) isProcessEvent_Event() {}

func (*ProcessEvent_End) isProcessEvent_Event() {}

func (*ProcessEvent_Start) isProcessEvent_Event() {}

func (*ProcessEvent_Keepalive) isProcessEvent_Event() {}

// StreamInputRequest is a request to send input to a process
type StreamInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Stdin         []byte                 `protobuf:"bytes,2,opt,name=stdin,proto3" json:"stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInputRequest) Reset() {
	*x = StreamInputRequest{}
	mi := &file_internal_proto_process_process_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInputRequest) ProtoMessage() {}

func (x *StreamInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInputRequest.ProtoReflect.Descriptor instead.
func (*StreamInputRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{4}
}

func (x *StreamInputRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StreamInputRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

// StreamInputResponse is the response from sending input
type StreamInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInputResponse) Reset() {
	*x = StreamInputResponse{}
	mi := &file_internal_proto_process_process_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInputResponse) ProtoMessage() {}

func (x *StreamInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInputResponse.ProtoReflect.Descriptor instead.
func (*StreamInputResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{5}
}

// KillRequest is a request to kill a process
type KillRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pid   uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// Signal to send (default SIGKILL = 9)
	Signal        *int32 `protobuf:"varint,2,opt,name=signal,proto3,oneof" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_internal_proto_process_process_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{6}
}

func (x *KillRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *KillRequest) GetSignal() int32 {
	if x != nil && x.Signal != nil {
		return *x.Signal
	}
	return 0
}

// KillResponse is the response from killing a process
type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Killed        bool                   `protobuf:"varint,1,opt,name=killed,proto3" json:"killed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_internal_proto_process_process_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{7}
}

func (x *KillResponse) GetKilled() bool {
	if x != nil {
		return x.Killed
	}
	return false
}

// ConnectRequest is a request to connect to a running process
type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_internal_proto_process_process_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// ListRequest is a request to list running processes
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_internal_proto_process_process_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{9}
}

// ProcessInfo contains information about a running process
type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Cmd           string                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Envs          map[string]string      `protobuf:"bytes,4,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd           string                 `protobuf:"bytes,5,opt,name=cwd,proto3" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_internal_proto_process_process_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{10}
}

func (x *ProcessInfo) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *ProcessInfo) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProcessInfo) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *ProcessInfo) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

// ListResponse is the response from listing processes
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_internal_proto_process_process_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{11}
}

func (x *ListResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

type ProcessEvent_DataEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent_DataEvent) Reset() {
	*x = ProcessEvent_DataEvent{}
	mi := &file_internal_proto_process_process_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent_DataEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent_DataEvent) ProtoMessage() {}

func (x *ProcessEvent_DataEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent_DataEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent_DataEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ProcessEvent_DataEvent) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ProcessEvent_DataEvent) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

type ProcessEvent_EndEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exited        bool                   `protobuf:"varint,1,opt,name=exited,proto3" json:"exited,omitempty"`
	ExitCode      *int32                 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	Killed        bool                   `protobuf:"varint,3,opt,name=killed,proto3" json:"killed,omitempty"`
	Signal        *int32                 `protobuf:"varint,4,opt,name=signal,proto3,oneof" json:"signal,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent_EndEvent) Reset() {
	*x = ProcessEvent_EndEvent{}
	mi := &file_internal_proto_process_process_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent_EndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent_EndEvent) ProtoMessage() {}

func (x *ProcessEvent_EndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent_EndEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent_EndEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ProcessEvent_EndEvent) GetExited() bool {
	if x != nil {
		return x.Exited
	}
	return false
}

func (x *ProcessEvent_EndEvent) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *ProcessEvent_EndEvent) GetKilled() bool {
	if x != nil {
		return x.Killed
	}
	return false
}

func (x *ProcessEvent_EndEvent) GetSignal() int32 {
	if x != nil && x.Signal != nil {
		return *x.Signal
	}
	return 0
}

func (x *ProcessEvent_EndEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProcessEvent_StartEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent_StartEvent) Reset() {
	*x = ProcessEvent_StartEvent{}
	mi := &file_internal_proto_process_process_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent_StartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent_StartEvent) ProtoMessage() {}

func (x *ProcessEvent_StartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent_StartEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent_StartEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{3, 2}
}

func (x *ProcessEvent_StartEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ProcessEvent_KeepAlive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent_KeepAlive) Reset() {
	*x = ProcessEvent_KeepAlive{}
	mi := &file_internal_proto_process_process_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent_KeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent_KeepAlive) ProtoMessage() {}

func (x *ProcessEvent_KeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_process_process_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent_KeepAlive.ProtoReflect.Descriptor instead.
func (*ProcessEvent_KeepAlive) Descriptor() ([]byte, []int) {
	return file_internal_proto_process_process_proto_rawDescGZIP(), []int{3, 3}
}

var File_internal_proto_process_process_proto protoreflect.FileDescriptor

const file_internal_proto_process_process_proto_rawDesc = "" +
	"\n" +
	"$internal/proto/process/process.proto\x12\aprocess\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x01\n" +
	"\rProcessConfig\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x124\n" +
	"\x04envs\x18\x03 \x03(\v2 .process.ProcessConfig.EnvsEntryR\x04envs\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\fStartRequest\x12.\n" +
	"\x06config\x18\x01 \x01(\v2\x16.process.ProcessConfigR\x06config\"!\n" +
	"\rStartResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\"\x92\x04\n" +
	"\fProcessEvent\x125\n" +
	"\x04data\x18\x01 \x01(\v2\x1f.process.ProcessEvent.DataEventH\x00R\x04data\x122\n" +
	"\x03end\x18\x02 \x01(\v2\x1e.process.ProcessEvent.EndEventH\x00R\x03end\x128\n" +
	"\x05start\x18\x03 \x01(\v2 .process.ProcessEvent.StartEventH\x00R\x05start\x12?\n" +
	"\tkeepalive\x18\x04 \x01(\v2\x1f.process.ProcessEvent.KeepAliveH\x00R\tkeepalive\x1a;\n" +
	"\tDataEvent\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\fR\x06stderr\x1a\xa8\x01\n" +
	"\bEndEvent\x12\x16\n" +
	"\x06exited\x18\x01 \x01(\bR\x06exited\x12 \n" +
	"\texit_code\x18\x02 \x01(\x05H\x00R\bexitCode\x88\x01\x01\x12\x16\n" +
	"\x06killed\x18\x03 \x01(\bR\x06killed\x12\x1b\n" +
	"\x06signal\x18\x04 \x01(\x05H\x01R\x06signal\x88\x01\x01\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05errorB\f\n" +
	"\n" +
	"_exit_codeB\t\n" +
	"\a_signal\x1a\x1e\n" +
	"\n" +
	"StartEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x1a\v\n" +
	"\tKeepAliveB\a\n" +
	"\x05event\"<\n" +
	"\x12StreamInputRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x14\n" +
	"\x05stdin\x18\x02 \x01(\fR\x05stdin\"\x15\n" +
	"\x13StreamInputResponse\"G\n" +
	"\vKillRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x1b\n" +
	"\x06signal\x18\x02 \x01(\x05H\x00R\x06signal\x88\x01\x01B\t\n" +
	"\a_signal\"&\n" +
	"\fKillResponse\x12\x16\n" +
	"\x06killed\x18\x01 \x01(\bR\x06killed\"\"\n" +
	"\x0eConnectRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\"\r\n" +
	"\vListRequest\"\xc4\x01\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x122\n" +
	"\x04envs\x18\x04 \x03(\v2\x1e.process.ProcessInfo.EnvsEntryR\x04envs\x12\x10\n" +
	"\x03cwd\x18\x05 \x01(\tR\x03cwd\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\fListResponse\x122\n" +
	"\tprocesses\x18\x01 \x03(\v2\x14.process.ProcessInfoR\tprocesses2\xb3\x02\n" +
	"\aProcess\x127\n" +
	"\x05Start\x12\x15.process.StartRequest\x1a\x15.process.ProcessEvent0\x01\x12;\n" +
	"\aConnect\x12\x17.process.ConnectRequest\x1a\x15.process.ProcessEvent0\x01\x12H\n" +
	"\vStreamInput\x12\x1b.process.StreamInputRequest\x1a\x1c.process.StreamInputResponse\x123\n" +
	"\x04Kill\x12\x14.process.KillRequest\x1a\x15.process.KillResponse\x123\n" +
	"\x04List\x12\x14.process.ListRequest\x1a\x15.process.ListResponseB=Z;github.com/xerpa-ai/e2b-go/internal/proto/process;processpbb\x06proto3"

var (
	file_internal_proto_process_process_proto_rawDescOnce sync.Once
	file_internal_proto_process_process_proto_rawDescData []byte
)

func file_internal_proto_process_process_proto_rawDescGZIP() []byte {
	file_internal_proto_process_process_proto_rawDescOnce.Do(func() {
		file_internal_proto_process_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_process_process_proto_rawDesc), len(file_internal_proto_process_process_proto_rawDesc)))
	})
	return file_internal_proto_process_process_proto_rawDescData
}

var file_internal_proto_process_process_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_internal_proto_process_process_proto_goTypes = []any{
	(*ProcessConfig)(nil),           // 0: process.ProcessConfig
	(*StartRequest)(nil),            // 1: process.StartRequest
	(*StartResponse)(nil),           // 2: process.StartResponse
	(*ProcessEvent)(nil),            // 3: process.ProcessEvent
	(*StreamInputRequest)(nil),      // 4: process.StreamInputRequest
	(*StreamInputResponse)(nil),     // 5: process.StreamInputResponse
	(*KillRequest)(nil),             // 6: process.KillRequest
	(*KillResponse)(nil),            // 7: process.KillResponse
	(*ConnectRequest)(nil),          // 8: process.ConnectRequest
	(*ListRequest)(nil),             // 9: process.ListRequest
	(*ProcessInfo)(nil),             // 10: process.ProcessInfo
	(*ListResponse)(nil),            // 11: process.ListResponse
	nil,                             // 12: process.ProcessConfig.EnvsEntry
	(*ProcessEvent_DataEvent)(nil),  // 13: process.ProcessEvent.DataEvent
	(*ProcessEvent_EndEvent)(nil),   // 14: process.ProcessEvent.EndEvent
	(*ProcessEvent_StartEvent)(nil), // 15: process.ProcessEvent.StartEvent
	(*ProcessEvent_KeepAlive)(nil),  // 16: process.ProcessEvent.KeepAlive
	nil,                             // 17: process.ProcessInfo.EnvsEntry
}
var file_internal_proto_process_process_proto_depIdxs = []int32{
	12, // 0: process.ProcessConfig.envs:type_name -> process.ProcessConfig.EnvsEntry
	0,  // 1: process.StartRequest.config:type_name -> process.ProcessConfig
	13, // 2: process.ProcessEvent.data:type_name -> process.ProcessEvent.DataEvent
	14, // 3: process.ProcessEvent.end:type_name -> process.ProcessEvent.EndEvent
	15, // 4: process.ProcessEvent.start:type_name -> process.ProcessEvent.StartEvent
	16, // 5: process.ProcessEvent.keepalive:type_name -> process.ProcessEvent.KeepAlive
	17, // 6: process.ProcessInfo.envs:type_name -> process.ProcessInfo.EnvsEntry
	10, // 7: process.ListResponse.processes:type_name -> process.ProcessInfo
	1,  // 8: process.Process.Start:input_type -> process.StartRequest
	8,  // 9: process.Process.Connect:input_type -> process.ConnectRequest
	4,  // 10: process.Process.StreamInput:input_type -> process.StreamInputRequest
	6,  // 11: process.Process.Kill:input_type -> process.KillRequest
	9,  // 12: process.Process.List:input_type -> process.ListRequest
	3,  // 13: process.Process.Start:output_type -> process.ProcessEvent
	3,  // 14: process.Process.Connect:output_type -> process.ProcessEvent
	5,  // 15: process.Process.StreamInput:output_type -> process.StreamInputResponse
	7,  // 16: process.Process.Kill:output_type -> process.KillResponse
	11, // 17: process.Process.List:output_type -> process.ListResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_proto_process_process_proto_init() }
func file_internal_proto_process_process_proto_init() {
	if File_internal_proto_process_process_proto != nil {
		return
	}
	file_internal_proto_process_process_proto_msgTypes[3].OneofWrappers = []any{
		(*ProcessEvent_Data)(nil),
		(*ProcessEvent_End)(nil),
		(*ProcessEvent_Start)(nil),
		(*ProcessEvent_Keepalive)(nil),
	}
	file_internal_proto_process_process_proto_msgTypes[6].OneofWrappers = []any{}
	file_internal_proto_process_process_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_process_process_proto_rawDesc), len(file_internal_proto_process_process_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_process_process_proto_goTypes,
		DependencyIndexes: file_internal_proto_process_process_proto_depIdxs,
		MessageInfos:      file_internal_proto_process_process_proto_msgTypes,
	}.Build()
	File_internal_proto_process_process_proto = out.File
	file_internal_proto_process_process_proto_goTypes = nil
	file_internal_proto_process_process_proto_depIdxs = nil
}
