// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: internal/proto/process/process.proto

package processpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	process "github.com/xerpa-ai/e2b-go/internal/proto/process"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProcessName is the fully-qualified name of the Process service.
	ProcessName = "process.Process"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProcessStartProcedure is the fully-qualified name of the Process's Start RPC.
	ProcessStartProcedure = "/process.Process/Start"
	// ProcessConnectProcedure is the fully-qualified name of the Process's Connect RPC.
	ProcessConnectProcedure = "/process.Process/Connect"
	// ProcessStreamInputProcedure is the fully-qualified name of the Process's StreamInput RPC.
	ProcessStreamInputProcedure = "/process.Process/StreamInput"
	// ProcessKillProcedure is the fully-qualified name of the Process's Kill RPC.
	ProcessKillProcedure = "/process.Process/Kill"
	// ProcessListProcedure is the fully-qualified name of the Process's List RPC.
	ProcessListProcedure = "/process.Process/List"
)

// ProcessClient is a client for the process.Process service.
type ProcessClient interface {
	// Start starts a new process and streams its output
	Start(context.Context, *connect.Request[process.StartRequest]) (*connect.ServerStreamForClient[process.ProcessEvent], error)
	// Connect connects to an already running process
	Connect(context.Context, *connect.Request[process.ConnectRequest]) (*connect.ServerStreamForClient[process.ProcessEvent], error)
	// StreamInput sends input to a process's stdin
	StreamInput(context.Context, *connect.Request[process.StreamInputRequest]) (*connect.Response[process.StreamInputResponse], error)
	// Kill terminates a process
	Kill(context.Context, *connect.Request[process.KillRequest]) (*connect.Response[process.KillResponse], error)
	// List lists all running processes
	List(context.Context, *connect.Request[process.ListRequest]) (*connect.Response[process.ListResponse], error)
}

// NewProcessClient constructs a client for the process.Process service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProcessClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProcessClient {
	baseURL = strings.TrimRight(baseURL, "/")
	processMethods := process.File_internal_proto_process_process_proto.Services().ByName("Process").Methods()
	return &processClient{
		start: connect.NewClient[process.StartRequest, process.ProcessEvent](
			httpClient,
			baseURL+ProcessStartProcedure,
			connect.WithSchema(processMethods.ByName("Start")),
			connect.WithClientOptions(opts...),
		),
		connect: connect.NewClient[process.ConnectRequest, process.ProcessEvent](
			httpClient,
			baseURL+ProcessConnectProcedure,
			connect.WithSchema(processMethods.ByName("Connect")),
			connect.WithClientOptions(opts...),
		),
		streamInput: connect.NewClient[process.StreamInputRequest, process.StreamInputResponse](
			httpClient,
			baseURL+ProcessStreamInputProcedure,
			connect.WithSchema(processMethods.ByName("StreamInput")),
			connect.WithClientOptions(opts...),
		),
		kill: connect.NewClient[process.KillRequest, process.KillResponse](
			httpClient,
			baseURL+ProcessKillProcedure,
			connect.WithSchema(processMethods.ByName("Kill")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[process.ListRequest, process.ListResponse](
			httpClient,
			baseURL+ProcessListProcedure,
			connect.WithSchema(processMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
	}
}

// processClient implements ProcessClient.
type processClient struct {
	start       *connect.Client[process.StartRequest, process.ProcessEvent]
	connect     *connect.Client[process.ConnectRequest, process.ProcessEvent]
	streamInput *connect.Client[process.StreamInputRequest, process.StreamInputResponse]
	kill        *connect.Client[process.KillRequest, process.KillResponse]
	list        *connect.Client[process.ListRequest, process.ListResponse]
}

// Start calls process.Process.Start.
func (c *processClient) Start(ctx context.Context, req *connect.Request[process.StartRequest]) (*connect.ServerStreamForClient[process.ProcessEvent], error) {
	return c.start.CallServerStream(ctx, req)
}

// Connect calls process.Process.Connect.
func (c *processClient) Connect(ctx context.Context, req *connect.Request[process.ConnectRequest]) (*connect.ServerStreamForClient[process.ProcessEvent], error) {
	return c.connect.CallServerStream(ctx, req)
}

// StreamInput calls process.Process.StreamInput.
func (c *processClient) StreamInput(ctx context.Context, req *connect.Request[process.StreamInputRequest]) (*connect.Response[process.StreamInputResponse], error) {
	return c.streamInput.CallUnary(ctx, req)
}

// Kill calls process.Process.Kill.
func (c *processClient) Kill(ctx context.Context, req *connect.Request[process.KillRequest]) (*connect.Response[process.KillResponse], error) {
	return c.kill.CallUnary(ctx, req)
}

// List calls process.Process.List.
func (c *processClient) List(ctx context.Context, req *connect.Request[process.ListRequest]) (*connect.Response[process.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// ProcessHandler is an implementation of the process.Process service.
type ProcessHandler interface {
	// Start starts a new process and streams its output
	Start(context.Context, *connect.Request[process.StartRequest], *connect.ServerStream[process.ProcessEvent]) error
	// Connect connects to an already running process
	Connect(context.Context, *connect.Request[process.ConnectRequest], *connect.ServerStream[process.ProcessEvent]) error
	// StreamInput sends input to a process's stdin
	StreamInput(context.Context, *connect.Request[process.StreamInputRequest]) (*connect.Response[process.StreamInputResponse], error)
	// Kill terminates a process
	Kill(context.Context, *connect.Request[process.KillRequest]) (*connect.Response[process.KillResponse], error)
	// List lists all running processes
	List(context.Context, *connect.Request[process.ListRequest]) (*connect.Response[process.ListResponse], error)
}

// NewProcessHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProcessHandler(svc ProcessHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	processMethods := process.File_internal_proto_process_process_proto.Services().ByName("Process").Methods()
	processStartHandler := connect.NewServerStreamHandler(
		ProcessStartProcedure,
		svc.Start,
		connect.WithSchema(processMethods.ByName("Start")),
		connect.WithHandlerOptions(opts...),
	)
	processConnectHandler := connect.NewServerStreamHandler(
		ProcessConnectProcedure,
		svc.Connect,
		connect.WithSchema(processMethods.ByName("Connect")),
		connect.WithHandlerOptions(opts...),
	)
	processStreamInputHandler := connect.NewUnaryHandler(
		ProcessStreamInputProcedure,
		svc.StreamInput,
		connect.WithSchema(processMethods.ByName("StreamInput")),
		connect.WithHandlerOptions(opts...),
	)
	processKillHandler := connect.NewUnaryHandler(
		ProcessKillProcedure,
		svc.Kill,
		connect.WithSchema(processMethods.ByName("Kill")),
		connect.WithHandlerOptions(opts...),
	)
	processListHandler := connect.NewUnaryHandler(
		ProcessListProcedure,
		svc.List,
		connect.WithSchema(processMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	return "/process.Process/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProcessStartProcedure:
			processStartHandler.ServeHTTP(w, r)
		case ProcessConnectProcedure:
			processConnectHandler.ServeHTTP(w, r)
		case ProcessStreamInputProcedure:
			processStreamInputHandler.ServeHTTP(w, r)
		case ProcessKillProcedure:
			processKillHandler.ServeHTTP(w, r)
		case ProcessListProcedure:
			processListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProcessHandler returns CodeUnimplemented from all methods.
type UnimplementedProcessHandler struct{}

func (UnimplementedProcessHandler) Start(context.Context, *connect.Request[process.StartRequest], *connect.ServerStream[process.ProcessEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("process.Process.Start is not implemented"))
}

func (UnimplementedProcessHandler) Connect(context.Context, *connect.Request[process.ConnectRequest], *connect.ServerStream[process.ProcessEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("process.Process.Connect is not implemented"))
}

func (UnimplementedProcessHandler) StreamInput(context.Context, *connect.Request[process.StreamInputRequest]) (*connect.Response[process.StreamInputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.Process.StreamInput is not implemented"))
}

func (UnimplementedProcessHandler) Kill(context.Context, *connect.Request[process.KillRequest]) (*connect.Response[process.KillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.Process.Kill is not implemented"))
}

func (UnimplementedProcessHandler) List(context.Context, *connect.Request[process.ListRequest]) (*connect.Response[process.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("process.Process.List is not implemented"))
}
